import '../../../core/phrase.dart';

class MentalAction {
  static const List<Phrase> phrases = [
    Phrase(
      text: 'Sit somewhere quiet and think',
      slot: PhraseSlot.action,
      affinityTags: ['sage', 'reflective', 'solemn'],
      categories: ['mental'],
      nature: QuestNature.action,
      shortTitle: 'Quiet Thinking',
    ),
    Phrase(
      text: 'Write down whatever is in your head right now',
      slot: PhraseSlot.action,
      affinityTags: ['reflective', 'scholar', 'moderate'],
      categories: ['mental'],
      nature: QuestNature.action,
      shortTitle: 'Brain Dump',
    ),
    Phrase(
      text: 'Read something completely unrelated to your day',
      slot: PhraseSlot.action,
      affinityTags: ['scholar', 'sage', 'solitary'],
      categories: ['mental'],
      nature: QuestNature.action,
      shortTitle: 'Read Something',
    ),
    Phrase(
      text: 'Sit and think about one thing you want to build or change',
      slot: PhraseSlot.action,
      affinityTags: ['mentor', 'philosophical', 'competitive'],
      categories: ['mental'],
      nature: QuestNature.action,
      shortTitle: 'Idea Session',
    ),
    Phrase(
      text: 'Put your phone down and sit with your thoughts',
      slot: PhraseSlot.action,
      affinityTags: ['sage', 'solemn', 'stoic'],
      categories: ['mental'],
      nature: QuestNature.action,
      shortTitle: 'Sit With It',
    ),
    Phrase(
      text: 'Spend 15 minutes doing nothing. No screens, no music.',
      slot: PhraseSlot.action,
      affinityTags: ['sage', 'stoic', 'solemn'],
      categories: ['mental'],
      nature: QuestNature.action,
      shortTitle: 'Do Nothing',
    ),
    Phrase(
      text: 'Write a list of everything that\'s been draining your energy lately',
      slot: PhraseSlot.action,
      affinityTags: ['reflective', 'warm', 'caretaker', 'scholar'],
      categories: ['mental'],
      nature: QuestNature.action,
      shortTitle: 'Energy Audit',
    ),
    Phrase(
      text: 'Think about one decision you\'ve been putting off. Decide.',
      slot: PhraseSlot.action,
      affinityTags: ['warrior', 'mentor', 'blunt', 'demanding'],
      categories: ['mental'],
      nature: QuestNature.action,
      shortTitle: 'Make the Call',
    ),
    Phrase(
      text: 'Write three things you want to stop doing. Be specific.',
      slot: PhraseSlot.action,
      affinityTags: ['mentor', 'competitive', 'reflective'],
      categories: ['mental'],
      nature: QuestNature.action,
      shortTitle: 'Stop Doing List',
    ),
    Phrase(
      text: 'Spend time with a problem you\'ve been avoiding. Just look at it.',
      slot: PhraseSlot.action,
      affinityTags: ['warrior', 'stoic', 'solemn', 'sage'],
      categories: ['mental'],
      nature: QuestNature.action,
      shortTitle: 'Face the Problem',
    ),
    Phrase(
      text: 'Pick one thought that keeps returning and write it out fully',
      slot: PhraseSlot.action,
      affinityTags: ['reflective', 'sage', 'scholar', 'solemn'],
      categories: ['mental'],
      nature: QuestNature.action,
      shortTitle: 'Unpack the Thought',
    ),
    Phrase(
      text: 'Meditate for 10 minutes. Breathing only.',
      slot: PhraseSlot.action,
      affinityTags: ['sage', 'stoic', 'gentle', 'solemn'],
      categories: ['mental'],
      nature: QuestNature.action,
      shortTitle: 'Breathe and Sit',
    ),

    // ── Character lines ───────────────────────────────────────────────────────

    Phrase(
      text: 'Think about ideas you can create.',
      slot: PhraseSlot.characterLine,
      affinityTags: ['mentor', 'warm', 'gentle', 'philosophical'],
      categories: ['mental'],
    ),
    Phrase(
      text: 'Think of one thing you can improve.',
      slot: PhraseSlot.characterLine,
      affinityTags: ['mentor', 'competitive', 'moderate'],
      categories: ['mental'],
    ),
    Phrase(
      text: 'Let the thought breathe.',
      slot: PhraseSlot.characterLine,
      affinityTags: ['sage', 'poetic', 'reflective', 'cryptic'],
      categories: ['mental'],
    ),
    Phrase(
      text: 'Your mind needs room to move.',
      slot: PhraseSlot.characterLine,
      affinityTags: ['sage', 'warm', 'moderate', 'philosophical'],
      categories: ['mental'],
    ),
    Phrase(
      text: 'Write it out. You\'ll see it differently.',
      slot: PhraseSlot.characterLine,
      affinityTags: ['mentor', 'scholar', 'reflective', 'blunt'],
      categories: ['mental'],
    ),
    Phrase(
      text: 'Don\'t try to solve anything. Just think.',
      slot: PhraseSlot.characterLine,
      affinityTags: ['sage', 'cryptic', 'solemn', 'reflective'],
      categories: ['mental'],
    ),
    Phrase(
      text: 'The noise outside won\'t stop. Start with the noise inside.',
      slot: PhraseSlot.characterLine,
      affinityTags: ['sage', 'solemn', 'philosophical'],
      categories: ['mental'],
    ),
    Phrase(
      text: 'Clarity doesn\'t arrive. You have to make space for it.',
      slot: PhraseSlot.characterLine,
      affinityTags: ['sage', 'cryptic', 'mentor', 'stoic'],
      categories: ['mental'],
    ),
    Phrase(
      text: 'You already know more than you think you do.',
      slot: PhraseSlot.characterLine,
      affinityTags: ['warm', 'mentor', 'caretaker', 'reflective'],
      categories: ['mental'],
    ),
  ];
}
