import '../../../core/phrase.dart';

class PhysicalAction {
  static const List<Phrase> phrases = [
    Phrase(
      text: 'Go outside and walk',
      slot: PhraseSlot.action,
      categories: ['physical'],
      nature: QuestNature.action,
      shortTitle: 'Take a Walk',
    ),
    Phrase(
      text: 'Go for a run',
      slot: PhraseSlot.action,
      affinityTags: ['warrior', 'demanding', 'competitive'],
      categories: ['physical'],
      nature: QuestNature.action,
      shortTitle: 'Go for a Run',
    ),
    Phrase(
      text: 'Do a set of pushups',
      slot: PhraseSlot.action,
      affinityTags: ['warrior', 'demanding', 'physical'],
      categories: ['physical'],
      nature: QuestNature.action,
      shortTitle: 'Pushup Set',
    ),
    Phrase(
      text: 'Stretch properly',
      slot: PhraseSlot.action,
      affinityTags: ['gentle', 'warm', 'caretaker'],
      categories: ['physical'],
      nature: QuestNature.action,
      shortTitle: 'Stretch It Out',
    ),
    Phrase(
      text: 'Take yourself for a slow walk',
      slot: PhraseSlot.action,
      affinityTags: ['warm', 'caretaker', 'reflective'],
      categories: ['physical'],
      nature: QuestNature.action,
      shortTitle: 'Slow Walk',
    ),
    Phrase(
      text: 'Find a set of stairs and climb them until your legs feel it',
      slot: PhraseSlot.action,
      affinityTags: ['warrior', 'trickster', 'explorer'],
      categories: ['physical'],
      nature: QuestNature.action,
      shortTitle: 'Stair Climb',
    ),
    Phrase(
      text: 'Do a full-body stretch from head to foot',
      slot: PhraseSlot.action,
      affinityTags: ['gentle', 'caretaker', 'moderate'],
      categories: ['physical'],
      nature: QuestNature.action,
      shortTitle: 'Full Stretch',
    ),
    Phrase(
      text: 'Do 10 minutes of any exercise. No stopping.',
      slot: PhraseSlot.action,
      affinityTags: ['warrior', 'demanding', 'stoic'],
      categories: ['physical'],
      nature: QuestNature.action,
      shortTitle: '10 Minute Push',
    ),
    Phrase(
      text: 'Go for a bike ride somewhere you\'ve been before',
      slot: PhraseSlot.action,
      affinityTags: ['explorer', 'wanderer', 'playful'],
      categories: ['physical'],
      nature: QuestNature.action,
      shortTitle: 'Bike Ride',
      requires: 'bike',
    ),
    Phrase(
      text: 'Do a bodyweight circuit. Pick four moves and repeat them.',
      slot: PhraseSlot.action,
      affinityTags: ['warrior', 'competitive', 'demanding'],
      categories: ['physical'],
      nature: QuestNature.action,
      shortTitle: 'Bodyweight Circuit',
    ),
    Phrase(
      text: 'Spend 20 minutes doing whatever physical activity feels right today',
      slot: PhraseSlot.action,
      affinityTags: ['gentle', 'warm', 'caretaker', 'moderate'],
      categories: ['physical'],
      nature: QuestNature.action,
      shortTitle: 'Move Your Way',
    ),
    Phrase(
      text: 'Spend time at the gym. Any goal.',
      slot: PhraseSlot.action,
      affinityTags: ['warrior', 'competitive', 'demanding'],
      categories: ['physical'],
      nature: QuestNature.action,
      shortTitle: 'Gym Session',
      requires: 'gym_access',
    ),
    Phrase(
      text: 'Jump rope for 5 minutes straight',
      slot: PhraseSlot.action,
      affinityTags: ['warrior', 'trickster', 'playful'],
      categories: ['physical'],
      nature: QuestNature.action,
      shortTitle: 'Jump Rope',
    ),
    Phrase(
      text: 'Hold a plank until failure. Rest. Do it again.',
      slot: PhraseSlot.action,
      affinityTags: ['warrior', 'stoic', 'demanding'],
      categories: ['physical'],
      nature: QuestNature.action,
      shortTitle: 'Plank Hold',
    ),
    Phrase(
      text: 'Go for a long walk with no destination. Just move.',
      slot: PhraseSlot.action,
      affinityTags: ['wanderer', 'reflective', 'solemn'],
      categories: ['physical'],
      nature: QuestNature.action,
      shortTitle: 'Wander Walk',
    ),

    // ── Character lines ───────────────────────────────────────────────────────

    Phrase(
      text: 'Push until your body remembers it\'s alive.',
      slot: PhraseSlot.characterLine,
      affinityTags: ['warrior', 'demanding', 'competitive', 'physical'],
      categories: ['physical'],
    ),
    Phrase(
      text: 'Feel where it gets hard. Stay there a moment.',
      slot: PhraseSlot.characterLine,
      affinityTags: ['warrior', 'stoic', 'demanding'],
      categories: ['physical'],
    ),
    Phrase(
      text: 'Your body knows what it needs.',
      slot: PhraseSlot.characterLine,
      affinityTags: ['caretaker', 'warm', 'gentle'],
      categories: ['physical'],
    ),
    Phrase(
      text: 'Let your legs do the thinking.',
      slot: PhraseSlot.characterLine,
      affinityTags: ['sage', 'cryptic', 'reflective'],
      categories: ['physical'],
    ),
    Phrase(
      text: 'Move like you mean it.',
      slot: PhraseSlot.characterLine,
      affinityTags: ['warrior', 'blunt', 'competitive'],
      categories: ['physical'],
    ),
    Phrase(
      text: 'Don\'t count reps. Count effort.',
      slot: PhraseSlot.characterLine,
      affinityTags: ['warrior', 'mentor', 'stoic'],
      categories: ['physical'],
    ),
    Phrase(
      text: 'Your body keeps score. Make it count.',
      slot: PhraseSlot.characterLine,
      affinityTags: ['warrior', 'solemn', 'demanding'],
      categories: ['physical'],
    ),
    Phrase(
      text: 'Let the movement clear your head.',
      slot: PhraseSlot.characterLine,
      affinityTags: ['warm', 'gentle', 'reflective', 'caretaker'],
      categories: ['physical'],
    ),
    Phrase(
      text: 'The only pace that matters is yours.',
      slot: PhraseSlot.characterLine,
      affinityTags: ['caretaker', 'warm', 'moderate'],
      categories: ['physical'],
    ),
  ];
}
